// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qekosvopyjoieuvgvfny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFla29zdm9weWpvaWV1dmd2Zm55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTUzMDEsImV4cCI6MjA3MTI5MTMwMX0.C-_K-zIU5Vi1Gyh7k0IuDAqq-mU6g43iP8aEGP0sRdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});